### ISSUE TITLE
X enters two digits

### ISSUE THREAD

**Issue by LuAusDu** [MikeCoder96/Xbox-PIN-Controller#1]
Pressing the x key inserts two digits instead of a 0.

The system on which this problem occurs uses the German keyboard layout.

**Comment by MikeCoder96** [comment]
Thanks for reporting the issue.

I've created this [commit](https://github.com/MikeCoder96/Xbox-PIN-Controller/commit/98bddfbfae0d77807faa019239043deaf0db2bf8) that solve the issue.

You can download the DLL [here](https://github.com/MikeCoder96/Xbox-PIN-Controller/releases/tag/v0.0.2), you have to just replace the **XboxPINController.dll**

Let me know.

**Comment by MikeCoder96** [comment]
#2

**Comment by MikeCoder96** [comment]
Fixed the X button.
Also, after some work, here a new pre-release without double buttons in short time. That worked for me (tried for a while now)
https://github.com/MikeCoder96/Xbox-PIN-Controller/releases/tag/v0.0.3

Hope this fix the problem
